### ISSUE TITLE
[DX] Adding automated releases and release notes

### ISSUE THREAD

**Issue by tamalCodes** [npci/falcon#1]
### Description

`DX (Developer Experience)`

Publishing releases (bumping up versions) and release notes are **super important** for any OSS project and we can do that automatically based on the Pull requests that are merged.
Here's what I offer. We can use [Release Drafter](https://github.com/release-drafter/release-drafter), a popular Opensource action that automatically creates Draft releases for you, along with proper semantic versioning.

&nbsp;

### How it works ?

- We can add up a `.github/workflows/release-drafter.yml` which will be responsible for drafting your releases based on the branches. 
- Then if you want "well-formatted" releases you can have `.github/release-drafter.yml` which will contain a template file and it will decide how the versioning is based upon labels `bug`, `feature`, and so on.
- Also it will help to format the labels with custom titles as per your choice.
&nbsp;

### Workflow and Demo

If you wish for a demo, head over to [Milan's Releases](https://github.com/MilanCommunity/Milan/releases) where we draft a release along with proper release notes as soon as we squash-merge a change to the `beta` branch. We publish a release every week when we merge our `beta` branch to the `main` branch.

It is fully based on the labels I add to the PR. If I add a `bug` it will be considered a `patch`, for `feature` it goes under the `minor` changes, and so on. Learn more about Semantic versioning [here](https://www.geeksforgeeks.org/introduction-semantic-versioning/)

### Screenshots

This is what draft changes look like 👇🏻

![image](https://github.com/rupali-codes/LinksHub/assets/72851613/c3e7ff56-4cef-4370-9e2a-9026bbd8b2c4)

This is how published changes look like 👇🏻

![image](https://github.com/rupali-codes/LinksHub/assets/72851613/956aedcd-5e38-45a6-a29d-d6b1f9c7e950)

### Checklist

- [X] I have checked the existing issues

**Comment by Burrito3000** [comment]
1. **Create a `.github/workflows/release-drafter.yml` File**: In your GitHub repository, create a folder named `.github/workflows` if it doesn't already exist. Inside this folder, create a file named `release-drafter.yml`. This file will define the GitHub Actions workflow for automating release drafting.

2. **Configure the Workflow**: Edit the `release-drafter.yml` file and define the GitHub Actions workflow. You'll need to specify when the workflow should trigger (e.g., when a pull request is merged), which branches to consider, and the steps to execute. You'll use the Release Drafter action in this workflow. Here's an example configuration:

```yaml
name: Release Drafter

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release-drafter.yml # Optional: If you want custom labels and formatting
```

3. **Create `.github/release-drafter.yml` File (Optional)**: If you want more control over the release notes' formatting and versioning, you can create a `.github/release-drafter.yml` file. This file will define how labels are mapped to version increments and how the release notes are formatted.

Here's an example configuration:

```yaml
name-template: 'v{{version}}'

categories:
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🚀 Features'
    label: 'feature'
  # Add more categories as needed

change-template: '- {{text}} (@{{author}})'

version-template: |
  ## {{version}}
  {{#each categories}}
  {{#if notes}}
  ### {{title}}

  {{#each notes}}
  {{{this}}}
  {{/each}}
  {{/if}}
  {{/each}}
```

4. **Label Pull Requests**: When you're creating or modifying pull requests, make sure to add the appropriate labels like "bug" or "feature" to categorize the changes.

With these steps in place, the GitHub Actions workflow will be triggered whenever a pull request is closed. Release Drafter will analyze the pull requests' labels, generate release notes, and draft a new release with semantic versioning based on the labels you've configured.
